const { colors } = require('tailwindcss/defaultTheme')

module.exports = {
  purge: false,
  theme: {
    fontSize: {
      xs: '.75rem',
      sm: '.875rem',
      tiny: '.875rem',
      base: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
      '2xl': '1.5rem',
      '3xl': '1.875rem',
      '4xl': '2.25rem',
      '5xl': '3rem',
      '6xl': '4rem',
      '7xl': '5rem',
      '8xl': '9rem',
    },
    minWidth: {
      '0': '0',
      '1/4': '25%',
      '1/2': '50%',
      '3/4': '75%',
      mb: '360px',
      full: '100%',
    },
    inset: {
      '0': 0,
      auto: 'auto',
      '50': '50%',
      '100': '100%',
    },
    fontFamily: {
      body: ['Helvetica', 'Arial', 'sans-serif'],
    },
    colors: {
      black: colors.black,
      white: colors.white,
      red: colors.red,
      yellow: colors.yellow,
      green: colors.green,
      blue: colors.blue,
      gray: {
        lighter: '#f9f9f9',
        default: 'rgb(244,244,244)',
        dark: 'rgb(100,101,105)',
        darkest: '#111111',
      },
      primary: {
        lighter: '#b3bcf5',
        default: '#c73443',
        dark: '#820c18',
      },
      secondary: {
        lighter: '#b3bcf5',
        default: 'rgb(56,85,105)',
        dark: '#202e78',
      },
    },
    zIndex: {
      '0': 0,
      '10': 10,
      '20': 20,
      '30': 30,
      '40': 40,
      '50': 50,
      '25': 25,
      '50': 50,
      '75': 75,
      '100': 100,
      '-10': -10,
      '-20': -20,
      '-30': -30,
      '-40': -40,
      '-50': -50,
      '-25': -25,
      '-50': -50,
      '-75': -75,
      '-100': -100,
    },
    container: {
      padding: {
        default: '2rem',
        sm: '2rem',
        lg: '2rem',
        xl: '0',
      },
    },
    extend: {
      lineHeight: {
        'extra-tight': '0.8',
      },
      maxWidth: {
        '150': '150px',
        mb: '360px',
      },
    },
  },
  variants: {
    display: [
      'responsive',
      'hover',
      'focus',
      'group-hover',
      'group-focus',
      'focus-within',
    ],
    zIndex: ['responsive'],
    margin: ['responsive', 'first', 'last'],
    padding: ['responsive', 'first', 'last'],
    borderWidth: ['responsive', 'first', 'last'],
  },
}
